### PR TITLE
sci-9302: make image tests and serving consistent

### PR DESCRIPTION
**Pull request by stufisher**
Need to check this is still performant as it does a few extra queries for the template parser

### CODE REVIEW

**Comment by stufisher** [comment]
@dsclassen

**Comment by stufisher** [comment]
Are the config variables correctly setup?

```
    # Visit directory on disk
    $visit_directory = '/dls/<%=BEAMLINENAME%>/data/<%=YEAR%>/<%=VISIT%>';

    # Diffraction image snapshots
    $jpeg_location = '<%=VISITDIR%>/jpegs/<%=IMDIRECTORY%>/<%=IMFILE%>.jpeg';
    $jpeg_thumb_location = '<%=VISITDIR%>/jpegs/<%=IMDIRECTORY%>/<%=IMFILE%>.thumb.jpeg';
```

**Comment by KarlLevik** [comment]
Not sure if relevant, but note that Diamond has visit directories as both `/dls/$beamline/data/$year/$visit` and `/dls/mx/data/$proposal/$visit` .

**Comment by stufisher** [comment]
Yes and because we no longer have the image table, we have to pick to support only one.

**Comment by drnasmith** [comment]
Yes the config.php property is the same as that set in the config_sample.php file.

**Comment by stufisher** [comment]
Urgh was caching the visit dir which was wrong

**Pull request merged**
