### PR TITLE
LIMS-216: Fix message for industrial archived visits

### PR DESCRIPTION
**Pull request by ndg63276**
Ticket: [LIMS-216](https://jira.diamond.ac.uk/browse/LIMS-216)

Clarify that data from 'archived' industrial visits is deleted, not archived.

### CODE REVIEW

**Review by KarlLevik — COMMENTED** [review]
It seems to be giving identical messages, whether it's an IN visit or not? 

I believe that last message should not say the visit is archived?

**Comment by ndg63276** [comment]
All visits are archived, but the difference is whether the data within that visit is archived or deleted.

**Comment by KarlLevik** [comment]
> All visits are archived, but the difference is whether the data within that visit is archived or deleted.

Hmm, that sounds confusing. What does it mean for a visit to be archive without its data? Perhaps better for the message then to say whether the visit *data* has been archived or not.

**Review by KarlLevik — APPROVED** [review]
The messages are now spot on!

I have no idea about the HTML, but presumably it works!

**Comment by NKatti2011** [comment]
Reopen pull request.

**Comment by NKatti2011** [comment]
LGTM.

**Pull request merged**
