### PR TITLE
Client build fixes

### PR DESCRIPTION
**Pull request by jlmuir**

### CODE REVIEW

**Comment by stufisher** [comment]
I dont think you should need to do this i need to check. Webpack uses the homepage variable to tell it if the root build is not /?

**Comment by jlmuir** [comment]
As far as I can tell, I need it.  But yes, please check since I know next to nothing about webpack.  What do you mean by "homepage variable"?  I don't know what that is.  Am I supposed to set it somewhere?  FWIW, I tried with `apiurl` and `appurl` set to `/synchweb/api` and `/synchweb`, respectively, in `config.json`, and it didn't work (e.g., paths in `index.php` were wrong).

**Comment by stufisher** [comment]
No you are absolutely right, these are needed. I've been working a lot with create-react-app recently and that has a "homepage": "/synchweb" variable you can add to package.json. Sorry for confusion!

**Comment by drnasmith** [comment]
If we move to the vue-router approach (a fork in preparation)  it has a similar 'base' setting which does the same thing for the client.
Remember if you have a different apiurl the apache or nginx config needs to match.

**Comment by drnasmith** [comment]
Plan to close this as webpack has been removed from titles.
Also base app url will be set via vue-router in latest vue master.

**Comment by morybc** [comment]
Closing off, to tidy up codebase - this is over two years old and does not appear to be needed.  Please reopen with clear explanation of what it is supposed to achieve, if the change is desired to be kept.

**Pull request closed without merging**
